### ISSUE TITLE
无法下载/tree/main/下的/data目录

### ISSUE THREAD

**Issue by twanghey** [xieincz/huggingface-go#1]

**Comment by xieincz** [comment]
请提供huggingface的链接

**Comment by twanghey** [comment]
<img width="1478" alt="image" src="https://github.com/xieincz/huggingface-go/assets/13992801/2c4c594e-50d3-479c-8f34-28f0d5589b7e">
https://huggingface.co/datasets/Skywork/SkyPile-150B/tree/main

**Comment by yzlnew** [comment]
指定到文件名也不行，会下载一个文件夹下来

**Comment by xieincz** [comment]
已经更新，现在的版本可以自己递归地下载文件夹中的文件。不过近期不考虑实现指定单个文件地下载这个功能，因为开发目的就是减少重复操作。若只想下载单个文件，完全可以在浏览器中点击下载按钮。

**Comment by yzlnew** [comment]
试了下还是 SkyPile 这个数据集，现在下到 `2022-05_zh_middle_0000.jsonl` 就退出了。因为后面的数据分片需要点 `load_more_files` 才可以访问到。
