### ISSUE TITLE
请问需要hf login的该如何处理

### ISSUE THREAD

**Issue by yisuanwang** [xieincz/huggingface-go#4]
RT🥹绿裙uu谢谢大佬

**Comment by xieincz** [comment]
这个要看你愿不愿意把自己的登录信息传给cf worker。你看了我的博客就会知道这个程序是依靠cf worker先帮你下载好文件，然后再从worker取回。

**Comment by Kurisu0306** [comment]
> 这个要看你愿不愿意把自己的登录信息传给cf worker。你看了我的博客就会知道这个程序是依靠cf worker先帮你下载好文件，然后再从worker取回。

请问该如何将自己的login信息传给worker，从浏览器传Cookie过去吗

**Comment by CatPetrova** [comment]
> 这个要看你愿不愿意把自己的登录信息传给cf worker。你看了我的博客就会知道这个程序是依靠cf worker先帮你下载好文件，然后再从worker取回。

怎么传递登陆信息呢？
