### ISSUE TITLE
无法完整下载

### ISSUE THREAD

**Issue by xjw00654** [xieincz/huggingface-go#5]
例如对于Qwen-72B https://huggingface.co/Qwen/Qwen-72B-Chat/tree/main 来说 只能加载页面上的39个包，load more之后的剩余的40+包无法获取到链接

**Comment by Kurisu0306** [comment]
确实，遇到了同样的问题

**Comment by xieincz** [comment]
这个功能我最快要1个月后才有时间写。赶着用的同学可以自己尝试去实现。大概思路就是检测到有load more这个关键词之后就发一个请求获取完整版的html。

**Comment by xjw00654** [comment]
看了一下 dataProps的那个json里面会有一个nextURL字段。
没写过go 我试试 0.0

**Comment by xieincz** [comment]
刚才更新的版本已经解决了这个问题
