### ISSUE TITLE
报错data-props attribute not found

### ISSUE THREAD

**Issue by Kurisu0306** [xieincz/huggingface-go#6]
执行命令： ./huggingface_go -u https://huggingface.co/datasets/imagenet-1k/  -f ./data -p （我的代理链接）
model/datasets name: imagenet-1k
model/datasets url: https://huggingface.co/datasets/imagenet-1k
fetching file list... 
this may take a while
current url: https://huggingface.co/datasets/imagenet-1k/tree/main
current proxy url: xxx
cannot fetch entries: data-props attribute not found

**Comment by xieincz** [comment]
这个数据集要求登录账号才能访问，相关的讨论见这个issue
https://github.com/xieincz/huggingface-go/issues/4
