### ISSUE TITLE
代理经常会出现掉速的问题，考不考虑添加镜像模式，直接用镜像站的链接下载

### ISSUE THREAD

**Issue by twanghey** [xieincz/huggingface-go#7]

**Comment by void-echo** [comment]
如果有好用的镜像，就没必要用这个工具了。请问你用的哪家镜像？

**Comment by twanghey** [comment]
> 如果有好用的镜像，就没必要用这个工具了。请问你用的哪家镜像？

https://hf-mirror.com/datasets，需要这个工具在服务器上直接下载，还是非常方便的，你可以看看这个镜像

**Comment by xieincz** [comment]
刚刚更新的 [V10](https://github.com/xieincz/huggingface-go/releases/tag/v10) 已经支持下载镜像站的文件
